# Generated by Django 3.2.5 on 2021-07-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
    ]
