# Generated by Django 3.2.5 on 2021-07-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_rename_features_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
